"""fixed users

Revision ID: 173bea267b74
Revises: e2f5049f1378
Create Date: 2020-11-11 15:45:55.532468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173bea267b74'
down_revision = 'e2f5049f1378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
